#!/bin/sh

while read line; do
  CREDS="${line}"
done < /dev/stdin

if [ -z "$CREDS" ]; then
  echo "No creds provided to STDIN"
  exit 3
fi

USERNAME=$(echo ${CREDS} | cut -d' ' -f1)
APIKEY=$(echo ${CREDS} | cut -d' ' -f2)

TOKEN=$(curl -s https://identity.api.rackspacecloud.com/v2.0/tokens \
  -X POST \
  -d "{\"auth\":{\"RAX-KSKEY:apiKeyCredentials\":{\"username\":\"$USERNAME\", \"apiKey\":\"$APIKEY\"}}}" \
  -H "Content-Type: application/json" | jq -r '.access.token.id // empty')

if [ -n "$TOKEN" ]; then
  exit 0
else
  exit 1
fi
