#!/usr/bin/env bash

while read line; do
  CREDS="${line}"
done < /dev/stdin

if [ -z "$CREDS" ]; then
  echo "No creds provided to STDIN"
  exit 3
fi

ARRAY=($CREDS)
USERNAME=${ARRAY[0]}
APIKEY=${ARRAY[1]}

TOKEN=$(curl -s https://identity.api.rackspacecloud.com/v2.0/tokens \
  -X POST \
  -d "{\"auth\":{\"RAX-KSKEY:apiKeyCredentials\":{\"username\":\"$USERNAME\", \"apiKey\":\"$APIKEY\"}}}" \
  -H "Content-Type: application/json" | /jq '.access.token.id')

if [ -n "$TOKEN" ]; then
  exit 0
else
  exit 1
fi
